VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "clsPackInfo"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

'==============================================================================
' CLASS: clsPackInfo
' PURPOSE: Store pack information
'==============================================================================

Public PackName As String
Public PackCode As String
Public ColumnIndex As Long
